### ISSUE TITLE
isnot working

### ISSUE THREAD

**Issue by asdashjdbasd** [Asseken/3Xui-ForSeparate#1]
(0x7ff62a8de040,0xc00080afe0)
2024/02/24 18:14:10 x-ui 0.1.0
(0x7ff62a8de040,0xc00080b0e0)
2024/02/24 18:14:10 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/02/24 18:14:10 unknown time zone Asia/Tehran
every time

**Comment by Asseken** [comment]
> (0x7ff62a8de040,0xc00080afe0)
> 
> 2024/02/24 18:14:10 x-ui 0.1.0
> 
> (0x7ff62a8de040,0xc00080b0e0)
> 
> 2024/02/24 18:14:10 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
> 
> 2024/02/24 18:14:10 unknown time zone Asia/Tehran
> 
> every time

** Hello, can you provide a screenshot? What system architecture are you running on**

**Comment by asdashjdbasd** [comment]
amd64

**Comment by asdashjdbasd** [comment]
![Uploading Untitled.png…]()

**Comment by asdashjdbasd** [comment]
![Untitled](https://github.com/Asseken/3Xui-ForSeparate/assets/132274784/042c205f-0383-417f-8c37-87c8d497fd22)

**Comment by asdashjdbasd** [comment]
![Untitled](https://github.com/Asseken/3Xui-ForSeparate/assets/132274784/abcbe91d-2dd1-4937-a6ac-48fe175e2331)
i tried it in 3 different system

**Comment by Asseken** [comment]
You can try changing your system's time zone.What is your time zone?
go 1.21 
Windows 7 support has been removed.

**Comment by asdashjdbasd** [comment]
thanx but i changed it to NY and no response my timezone is asia tehran
no one use windows 7 anymore i'm in windows 10
already installed go 1.21
and i said it before i test your program in three different system same error

**Comment by Asseken** [comment]
> thanx but i changed it to NY and no response my timezone is asia tehran no one use windows 7 anymore i'm in windows 10 already installed go 1.21 and i said it before i test your program in three different system same error
You can try to compile it yourself. Download the source code and enter the source code directory, run go build on the terminal, then copy the front-end files to the etc/html directory in the same directory as the program, and run the program

**Comment by asdashjdbasd** [comment]
After compiling your code thousand times finaly worked corectly. in several amd64 windows 10 system have been tested i put it in this link just check it please one more things i added xray core latest version [https://file.io/xivr42Lt1tjw](url)
Thankyou a lot
keep going
i would be appericate if you do ver 2.2.1 of MHSanaei

**Comment by Asseken** [comment]
> After compiling your code thousand times finaly worked corectly. in several amd64 windows 10 system have been tested i put it in this link just check it please one more things i added xray core latest version [https://file.io/xivr42Lt1tjw](url) Thankyou a lot keep going i would be appericate if you do ver 2.2.1 of MHSanaei

Already updated to the latest version v2.2.6
